FROM postgres:15-alpine

# Copy initialization script
COPY ./resources/database/init.sql /docker-entrypoint-initdb.d/

# Set environment variables
ENV POSTGRES_DB=fishshopp
ENV POSTGRES_USER=fishshop_user

# Expose port
EXPOSE 5432
